services:
  api:
    image: nerine
    restart: unless-stopped
    ports:
      - 127.0.0.1:3333:3333
    volumes:
      - ./event.toml:/app/event.toml
      - ./docker/attachments:/attachments
    environment:
      RUST_LOG: debug
      CORS_ORIGIN: "http://nerine.localhost"
      DATABASE_URL: postgres://postgres:postgres@db/nerine
      JWT_SECRET: ZXhhbXBsZV9zZWNyZXQK
      ADMIN_TOKEN: example_admin_token
      EVENT_PATH: /app/event.toml
  frontend:
    image: nerine-frontend
    restart: unless-stopped
    ports:
      - 127.0.0.1:3334:3334
    environment:
      HOST: 0.0.0.0
      API_BASE: "http://api:3333/api"
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    # temp
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: nerine
      POSTGRES_PASSWORD: postgres
